### ISSUE TITLE
Default color should be LXPanel's current text color

### ISSUE THREAD

**Issue by micrococo** [acamargovieira/plamelx#2]
Hi.

If you leave the Custom color field empty, plamelx should use the current text color set by LXPanel instead of a default fixed color. If it doesn't then you may end with unreadable text (black text on dark background panel color/image for example). I think that by doing this plamelx is more user friendly.

Greetings.

**Comment by acamargovieira** [comment]
Hi,

Thank you for reporting your experience with Plamelx.
The problem is that the LXPanel font color information is private and I could not get it to use in Plamelx.
To access this information it is necessary to integrate the Plamelx plugin code into the LXPanel code.
I do not have enough time and motivation to get in touch with the LXDE project and try to integrate Plamelx with LXPanel.
The color customization field exists precisely because I could not get the color information from LXPanel.
When I have time I will try to get the color information in another way.

Thank you

**Comment by acamargovieira** [comment]
Hi,

I just posted a new version(1.0.4) with the change you suggested, now Plamelx gets the same font color as LXPanel.

Greetings

**Comment by micrococo** [comment]
Thank you very much!
